USE [GCHAIN]

-- [Ca_Address] ----------------------
IF NOT EXISTS(SELECT * FROM sysobjects WHERE [name]='Ca_Address' AND xtype='U')

BEGIN

    CREATE TABLE Ca_Address ([ID] BIGINT NOT NULL
        ,[Createdat] BIGINT NOT NULL
        ,[Updatedat] BIGINT NOT NULL
        ,[Sort] BIGINT NOT NULL,
        [Caption] NVARCHAR(256) COLLATE Chinese_PRC_CI_AS
        ,[Bind] BIGINT
        ,[Type] INT
        ,[Line1] NVARCHAR(300) COLLATE Chinese_PRC_CI_AS
        ,[Line2] NVARCHAR(300) COLLATE Chinese_PRC_CI_AS
        ,[State] NVARCHAR(16) COLLATE Chinese_PRC_CI_AS
        ,[County] NVARCHAR(16) COLLATE Chinese_PRC_CI_AS
        ,[Town] NVARCHAR(16) COLLATE Chinese_PRC_CI_AS
        ,[Contact] NVARCHAR(64) COLLATE Chinese_PRC_CI_AS
        ,[Tel] NVARCHAR(20) COLLATE Chinese_PRC_CI_AS
        ,[Email] NVARCHAR(256) COLLATE Chinese_PRC_CI_AS
        ,[Zip] NVARCHAR(16) COLLATE Chinese_PRC_CI_AS
        ,[City] BIGINT
        ,[Country] BIGINT
        ,[Remarks] NVARCHAR(MAX)
, CONSTRAINT [PK_Ca_Address] PRIMARY KEY CLUSTERED ([ID] ASC)) ON [PRIMARY]
END


IF EXISTS(SELECT * FROM SYSCOLUMNS WHERE id=object_id('Ca_Address') AND name='Caption')
BEGIN
 ALTER TABLE Ca_Address ALTER COLUMN [Caption] NVARCHAR(256) COLLATE Chinese_PRC_CI_AS
END
ELSE
BEGIN
 ALTER TABLE Ca_Address ADD [Caption] NVARCHAR(256) COLLATE Chinese_PRC_CI_AS
END


IF EXISTS(SELECT * FROM SYSCOLUMNS WHERE id=object_id('Ca_Address') AND name='Bind')
BEGIN
 ALTER TABLE Ca_Address ALTER COLUMN [Bind] BIGINT
END
ELSE
BEGIN
 ALTER TABLE Ca_Address ADD [Bind] BIGINT
END


IF EXISTS(SELECT * FROM SYSCOLUMNS WHERE id=object_id('Ca_Address') AND name='Type')
BEGIN
 ALTER TABLE Ca_Address ALTER COLUMN [Type] INT
END
ELSE
BEGIN
 ALTER TABLE Ca_Address ADD [Type] INT
END


IF EXISTS(SELECT * FROM SYSCOLUMNS WHERE id=object_id('Ca_Address') AND name='Line1')
BEGIN
 ALTER TABLE Ca_Address ALTER COLUMN [Line1] NVARCHAR(300) COLLATE Chinese_PRC_CI_AS
END
ELSE
BEGIN
 ALTER TABLE Ca_Address ADD [Line1] NVARCHAR(300) COLLATE Chinese_PRC_CI_AS
END


IF EXISTS(SELECT * FROM SYSCOLUMNS WHERE id=object_id('Ca_Address') AND name='Line2')
BEGIN
 ALTER TABLE Ca_Address ALTER COLUMN [Line2] NVARCHAR(300) COLLATE Chinese_PRC_CI_AS
END
ELSE
BEGIN
 ALTER TABLE Ca_Address ADD [Line2] NVARCHAR(300) COLLATE Chinese_PRC_CI_AS
END


IF EXISTS(SELECT * FROM SYSCOLUMNS WHERE id=object_id('Ca_Address') AND name='State')
BEGIN
 ALTER TABLE Ca_Address ALTER COLUMN [State] NVARCHAR(16) COLLATE Chinese_PRC_CI_AS
END
ELSE
BEGIN
 ALTER TABLE Ca_Address ADD [State] NVARCHAR(16) COLLATE Chinese_PRC_CI_AS
END


IF EXISTS(SELECT * FROM SYSCOLUMNS WHERE id=object_id('Ca_Address') AND name='County')
BEGIN
 ALTER TABLE Ca_Address ALTER COLUMN [County] NVARCHAR(16) COLLATE Chinese_PRC_CI_AS
END
ELSE
BEGIN
 ALTER TABLE Ca_Address ADD [County] NVARCHAR(16) COLLATE Chinese_PRC_CI_AS
END


IF EXISTS(SELECT * FROM SYSCOLUMNS WHERE id=object_id('Ca_Address') AND name='Town')
BEGIN
 ALTER TABLE Ca_Address ALTER COLUMN [Town] NVARCHAR(16) COLLATE Chinese_PRC_CI_AS
END
ELSE
BEGIN
 ALTER TABLE Ca_Address ADD [Town] NVARCHAR(16) COLLATE Chinese_PRC_CI_AS
END


IF EXISTS(SELECT * FROM SYSCOLUMNS WHERE id=object_id('Ca_Address') AND name='Contact')
BEGIN
 ALTER TABLE Ca_Address ALTER COLUMN [Contact] NVARCHAR(64) COLLATE Chinese_PRC_CI_AS
END
ELSE
BEGIN
 ALTER TABLE Ca_Address ADD [Contact] NVARCHAR(64) COLLATE Chinese_PRC_CI_AS
END


IF EXISTS(SELECT * FROM SYSCOLUMNS WHERE id=object_id('Ca_Address') AND name='Tel')
BEGIN
 ALTER TABLE Ca_Address ALTER COLUMN [Tel] NVARCHAR(20) COLLATE Chinese_PRC_CI_AS
END
ELSE
BEGIN
 ALTER TABLE Ca_Address ADD [Tel] NVARCHAR(20) COLLATE Chinese_PRC_CI_AS
END


IF EXISTS(SELECT * FROM SYSCOLUMNS WHERE id=object_id('Ca_Address') AND name='Email')
BEGIN
 ALTER TABLE Ca_Address ALTER COLUMN [Email] NVARCHAR(256) COLLATE Chinese_PRC_CI_AS
END
ELSE
BEGIN
 ALTER TABLE Ca_Address ADD [Email] NVARCHAR(256) COLLATE Chinese_PRC_CI_AS
END


IF EXISTS(SELECT * FROM SYSCOLUMNS WHERE id=object_id('Ca_Address') AND name='Zip')
BEGIN
 ALTER TABLE Ca_Address ALTER COLUMN [Zip] NVARCHAR(16) COLLATE Chinese_PRC_CI_AS
END
ELSE
BEGIN
 ALTER TABLE Ca_Address ADD [Zip] NVARCHAR(16) COLLATE Chinese_PRC_CI_AS
END


IF EXISTS(SELECT * FROM SYSCOLUMNS WHERE id=object_id('Ca_Address') AND name='City')
BEGIN
 ALTER TABLE Ca_Address ALTER COLUMN [City] BIGINT
END
ELSE
BEGIN
 ALTER TABLE Ca_Address ADD [City] BIGINT
END


IF EXISTS(SELECT * FROM SYSCOLUMNS WHERE id=object_id('Ca_Address') AND name='Country')
BEGIN
 ALTER TABLE Ca_Address ALTER COLUMN [Country] BIGINT
END
ELSE
BEGIN
 ALTER TABLE Ca_Address ADD [Country] BIGINT
END


IF EXISTS(SELECT * FROM SYSCOLUMNS WHERE id=object_id('Ca_Address') AND name='Remarks')
BEGIN
 ALTER TABLE Ca_Address ALTER COLUMN [Remarks] NVARCHAR(MAX)
END
ELSE
BEGIN
 ALTER TABLE Ca_Address ADD [Remarks] NVARCHAR(MAX)
END

-- [Ca_Biz] ----------------------
IF NOT EXISTS(SELECT * FROM sysobjects WHERE [name]='Ca_Biz' AND xtype='U')

BEGIN

    CREATE TABLE Ca_Biz ([ID] BIGINT NOT NULL
        ,[Createdat] BIGINT NOT NULL
        ,[Updatedat] BIGINT NOT NULL
        ,[Sort] BIGINT NOT NULL,
        [Code] NVARCHAR(256) COLLATE Chinese_PRC_CI_AS
        ,[Caption] NVARCHAR(256) COLLATE Chinese_PRC_CI_AS
        ,[Parent] BIGINT
        ,[BasicAcct] BIGINT
        ,[Desc] NVARCHAR(MAX)
        ,[Website] NVARCHAR(256) COLLATE Chinese_PRC_CI_AS
        ,[Icon] NVARCHAR(256) COLLATE Chinese_PRC_CI_AS
        ,[City] BIGINT
        ,[Country] BIGINT
        ,[Lang] BIGINT
        ,[IsSocial] BIT
        ,[IsCmsSource] BIT
        ,[IsPay] BIT
        ,[MomentLatest] BIGINT
        ,[CountFollowers] BIGINT
        ,[CountFollows] BIGINT
        ,[CountMoments] BIGINT
        ,[CountViews] BIGINT
        ,[CountComments] BIGINT
        ,[CountThumbUps] BIGINT
        ,[CountThumbDns] BIGINT
        ,[IsCrawling] BIT
        ,[IsGSeries] BIT
        ,[RemarksCentral] NVARCHAR(MAX)
        ,[Agent] BIGINT
        ,[SiteCats] NVARCHAR(MAX)
        ,[ConfiguredCats] NVARCHAR(MAX)
, CONSTRAINT [PK_Ca_Biz] PRIMARY KEY CLUSTERED ([ID] ASC)) ON [PRIMARY]
END


IF EXISTS(SELECT * FROM SYSCOLUMNS WHERE id=object_id('Ca_Biz') AND name='Code')
BEGIN
 ALTER TABLE Ca_Biz ALTER COLUMN [Code] NVARCHAR(256) COLLATE Chinese_PRC_CI_AS
END
ELSE
BEGIN
 ALTER TABLE Ca_Biz ADD [Code] NVARCHAR(256) COLLATE Chinese_PRC_CI_AS
END


IF EXISTS(SELECT * FROM SYSCOLUMNS WHERE id=object_id('Ca_Biz') AND name='Caption')
BEGIN
 ALTER TABLE Ca_Biz ALTER COLUMN [Caption] NVARCHAR(256) COLLATE Chinese_PRC_CI_AS
END
ELSE
BEGIN
 ALTER TABLE Ca_Biz ADD [Caption] NVARCHAR(256) COLLATE Chinese_PRC_CI_AS
END


IF EXISTS(SELECT * FROM SYSCOLUMNS WHERE id=object_id('Ca_Biz') AND name='Parent')
BEGIN
 ALTER TABLE Ca_Biz ALTER COLUMN [Parent] BIGINT
END
ELSE
BEGIN
 ALTER TABLE Ca_Biz ADD [Parent] BIGINT
END


IF EXISTS(SELECT * FROM SYSCOLUMNS WHERE id=object_id('Ca_Biz') AND name='BasicAcct')
BEGIN
 ALTER TABLE Ca_Biz ALTER COLUMN [BasicAcct] BIGINT
END
ELSE
BEGIN
 ALTER TABLE Ca_Biz ADD [BasicAcct] BIGINT
END


IF EXISTS(SELECT * FROM SYSCOLUMNS WHERE id=object_id('Ca_Biz') AND name='Desc')
BEGIN
 ALTER TABLE Ca_Biz ALTER COLUMN [Desc] NVARCHAR(MAX)
END
ELSE
BEGIN
 ALTER TABLE Ca_Biz ADD [Desc] NVARCHAR(MAX)
END


IF EXISTS(SELECT * FROM SYSCOLUMNS WHERE id=object_id('Ca_Biz') AND name='Website')
BEGIN
 ALTER TABLE Ca_Biz ALTER COLUMN [Website] NVARCHAR(256) COLLATE Chinese_PRC_CI_AS
END
ELSE
BEGIN
 ALTER TABLE Ca_Biz ADD [Website] NVARCHAR(256) COLLATE Chinese_PRC_CI_AS
END


IF EXISTS(SELECT * FROM SYSCOLUMNS WHERE id=object_id('Ca_Biz') AND name='Icon')
BEGIN
 ALTER TABLE Ca_Biz ALTER COLUMN [Icon] NVARCHAR(256) COLLATE Chinese_PRC_CI_AS
END
ELSE
BEGIN
 ALTER TABLE Ca_Biz ADD [Icon] NVARCHAR(256) COLLATE Chinese_PRC_CI_AS
END


IF EXISTS(SELECT * FROM SYSCOLUMNS WHERE id=object_id('Ca_Biz') AND name='City')
BEGIN
 ALTER TABLE Ca_Biz ALTER COLUMN [City] BIGINT
END
ELSE
BEGIN
 ALTER TABLE Ca_Biz ADD [City] BIGINT
END


IF EXISTS(SELECT * FROM SYSCOLUMNS WHERE id=object_id('Ca_Biz') AND name='Country')
BEGIN
 ALTER TABLE Ca_Biz ALTER COLUMN [Country] BIGINT
END
ELSE
BEGIN
 ALTER TABLE Ca_Biz ADD [Country] BIGINT
END


IF EXISTS(SELECT * FROM SYSCOLUMNS WHERE id=object_id('Ca_Biz') AND name='Lang')
BEGIN
 ALTER TABLE Ca_Biz ALTER COLUMN [Lang] BIGINT
END
ELSE
BEGIN
 ALTER TABLE Ca_Biz ADD [Lang] BIGINT
END


IF EXISTS(SELECT * FROM SYSCOLUMNS WHERE id=object_id('Ca_Biz') AND name='IsSocial')
BEGIN
 ALTER TABLE Ca_Biz ALTER COLUMN [IsSocial] BIT
END
ELSE
BEGIN
 ALTER TABLE Ca_Biz ADD [IsSocial] BIT
END


IF EXISTS(SELECT * FROM SYSCOLUMNS WHERE id=object_id('Ca_Biz') AND name='IsCmsSource')
BEGIN
 ALTER TABLE Ca_Biz ALTER COLUMN [IsCmsSource] BIT
END
ELSE
BEGIN
 ALTER TABLE Ca_Biz ADD [IsCmsSource] BIT
END


IF EXISTS(SELECT * FROM SYSCOLUMNS WHERE id=object_id('Ca_Biz') AND name='IsPay')
BEGIN
 ALTER TABLE Ca_Biz ALTER COLUMN [IsPay] BIT
END
ELSE
BEGIN
 ALTER TABLE Ca_Biz ADD [IsPay] BIT
END


IF EXISTS(SELECT * FROM SYSCOLUMNS WHERE id=object_id('Ca_Biz') AND name='MomentLatest')
BEGIN
 ALTER TABLE Ca_Biz ALTER COLUMN [MomentLatest] BIGINT
END
ELSE
BEGIN
 ALTER TABLE Ca_Biz ADD [MomentLatest] BIGINT
END


IF EXISTS(SELECT * FROM SYSCOLUMNS WHERE id=object_id('Ca_Biz') AND name='CountFollowers')
BEGIN
 ALTER TABLE Ca_Biz ALTER COLUMN [CountFollowers] BIGINT
END
ELSE
BEGIN
 ALTER TABLE Ca_Biz ADD [CountFollowers] BIGINT
END


IF EXISTS(SELECT * FROM SYSCOLUMNS WHERE id=object_id('Ca_Biz') AND name='CountFollows')
BEGIN
 ALTER TABLE Ca_Biz ALTER COLUMN [CountFollows] BIGINT
END
ELSE
BEGIN
 ALTER TABLE Ca_Biz ADD [CountFollows] BIGINT
END


IF EXISTS(SELECT * FROM SYSCOLUMNS WHERE id=object_id('Ca_Biz') AND name='CountMoments')
BEGIN
 ALTER TABLE Ca_Biz ALTER COLUMN [CountMoments] BIGINT
END
ELSE
BEGIN
 ALTER TABLE Ca_Biz ADD [CountMoments] BIGINT
END


IF EXISTS(SELECT * FROM SYSCOLUMNS WHERE id=object_id('Ca_Biz') AND name='CountViews')
BEGIN
 ALTER TABLE Ca_Biz ALTER COLUMN [CountViews] BIGINT
END
ELSE
BEGIN
 ALTER TABLE Ca_Biz ADD [CountViews] BIGINT
END


IF EXISTS(SELECT * FROM SYSCOLUMNS WHERE id=object_id('Ca_Biz') AND name='CountComments')
BEGIN
 ALTER TABLE Ca_Biz ALTER COLUMN [CountComments] BIGINT
END
ELSE
BEGIN
 ALTER TABLE Ca_Biz ADD [CountComments] BIGINT
END


IF EXISTS(SELECT * FROM SYSCOLUMNS WHERE id=object_id('Ca_Biz') AND name='CountThumbUps')
BEGIN
 ALTER TABLE Ca_Biz ALTER COLUMN [CountThumbUps] BIGINT
END
ELSE
BEGIN
 ALTER TABLE Ca_Biz ADD [CountThumbUps] BIGINT
END


IF EXISTS(SELECT * FROM SYSCOLUMNS WHERE id=object_id('Ca_Biz') AND name='CountThumbDns')
BEGIN
 ALTER TABLE Ca_Biz ALTER COLUMN [CountThumbDns] BIGINT
END
ELSE
BEGIN
 ALTER TABLE Ca_Biz ADD [CountThumbDns] BIGINT
END


IF EXISTS(SELECT * FROM SYSCOLUMNS WHERE id=object_id('Ca_Biz') AND name='IsCrawling')
BEGIN
 ALTER TABLE Ca_Biz ALTER COLUMN [IsCrawling] BIT
END
ELSE
BEGIN
 ALTER TABLE Ca_Biz ADD [IsCrawling] BIT
END


IF EXISTS(SELECT * FROM SYSCOLUMNS WHERE id=object_id('Ca_Biz') AND name='IsGSeries')
BEGIN
 ALTER TABLE Ca_Biz ALTER COLUMN [IsGSeries] BIT
END
ELSE
BEGIN
 ALTER TABLE Ca_Biz ADD [IsGSeries] BIT
END


IF EXISTS(SELECT * FROM SYSCOLUMNS WHERE id=object_id('Ca_Biz') AND name='RemarksCentral')
BEGIN
 ALTER TABLE Ca_Biz ALTER COLUMN [RemarksCentral] NVARCHAR(MAX)
END
ELSE
BEGIN
 ALTER TABLE Ca_Biz ADD [RemarksCentral] NVARCHAR(MAX)
END


IF EXISTS(SELECT * FROM SYSCOLUMNS WHERE id=object_id('Ca_Biz') AND name='Agent')
BEGIN
 ALTER TABLE Ca_Biz ALTER COLUMN [Agent] BIGINT
END
ELSE
BEGIN
 ALTER TABLE Ca_Biz ADD [Agent] BIGINT
END


IF EXISTS(SELECT * FROM SYSCOLUMNS WHERE id=object_id('Ca_Biz') AND name='SiteCats')
BEGIN
 ALTER TABLE Ca_Biz ALTER COLUMN [SiteCats] NVARCHAR(MAX)
END
ELSE
BEGIN
 ALTER TABLE Ca_Biz ADD [SiteCats] NVARCHAR(MAX)
END


IF EXISTS(SELECT * FROM SYSCOLUMNS WHERE id=object_id('Ca_Biz') AND name='ConfiguredCats')
BEGIN
 ALTER TABLE Ca_Biz ALTER COLUMN [ConfiguredCats] NVARCHAR(MAX)
END
ELSE
BEGIN
 ALTER TABLE Ca_Biz ADD [ConfiguredCats] NVARCHAR(MAX)
END

-- [Ca_Country] ----------------------
IF NOT EXISTS(SELECT * FROM sysobjects WHERE [name]='Ca_Country' AND xtype='U')

BEGIN

    CREATE TABLE Ca_Country ([ID] BIGINT NOT NULL
        ,[Createdat] BIGINT NOT NULL
        ,[Updatedat] BIGINT NOT NULL
        ,[Sort] BIGINT NOT NULL,
        [Code2] NVARCHAR(2) COLLATE Chinese_PRC_CI_AS
        ,[Caption] NVARCHAR(64) COLLATE Chinese_PRC_CI_AS
        ,[Fullname] NVARCHAR(256) COLLATE Chinese_PRC_CI_AS
        ,[Icon] NVARCHAR(256) COLLATE Chinese_PRC_CI_AS
        ,[Tel] NVARCHAR(4) COLLATE Chinese_PRC_CI_AS
        ,[Cur] BIGINT
        ,[Capital] BIGINT
        ,[Place] BIGINT
        ,[Lang] BIGINT
, CONSTRAINT [PK_Ca_Country] PRIMARY KEY CLUSTERED ([ID] ASC)) ON [PRIMARY]
END


IF EXISTS(SELECT * FROM SYSCOLUMNS WHERE id=object_id('Ca_Country') AND name='Code2')
BEGIN
 ALTER TABLE Ca_Country ALTER COLUMN [Code2] NVARCHAR(2) COLLATE Chinese_PRC_CI_AS
END
ELSE
BEGIN
 ALTER TABLE Ca_Country ADD [Code2] NVARCHAR(2) COLLATE Chinese_PRC_CI_AS
END


IF EXISTS(SELECT * FROM SYSCOLUMNS WHERE id=object_id('Ca_Country') AND name='Caption')
BEGIN
 ALTER TABLE Ca_Country ALTER COLUMN [Caption] NVARCHAR(64) COLLATE Chinese_PRC_CI_AS
END
ELSE
BEGIN
 ALTER TABLE Ca_Country ADD [Caption] NVARCHAR(64) COLLATE Chinese_PRC_CI_AS
END


IF EXISTS(SELECT * FROM SYSCOLUMNS WHERE id=object_id('Ca_Country') AND name='Fullname')
BEGIN
 ALTER TABLE Ca_Country ALTER COLUMN [Fullname] NVARCHAR(256) COLLATE Chinese_PRC_CI_AS
END
ELSE
BEGIN
 ALTER TABLE Ca_Country ADD [Fullname] NVARCHAR(256) COLLATE Chinese_PRC_CI_AS
END


IF EXISTS(SELECT * FROM SYSCOLUMNS WHERE id=object_id('Ca_Country') AND name='Icon')
BEGIN
 ALTER TABLE Ca_Country ALTER COLUMN [Icon] NVARCHAR(256) COLLATE Chinese_PRC_CI_AS
END
ELSE
BEGIN
 ALTER TABLE Ca_Country ADD [Icon] NVARCHAR(256) COLLATE Chinese_PRC_CI_AS
END


IF EXISTS(SELECT * FROM SYSCOLUMNS WHERE id=object_id('Ca_Country') AND name='Tel')
BEGIN
 ALTER TABLE Ca_Country ALTER COLUMN [Tel] NVARCHAR(4) COLLATE Chinese_PRC_CI_AS
END
ELSE
BEGIN
 ALTER TABLE Ca_Country ADD [Tel] NVARCHAR(4) COLLATE Chinese_PRC_CI_AS
END


IF EXISTS(SELECT * FROM SYSCOLUMNS WHERE id=object_id('Ca_Country') AND name='Cur')
BEGIN
 ALTER TABLE Ca_Country ALTER COLUMN [Cur] BIGINT
END
ELSE
BEGIN
 ALTER TABLE Ca_Country ADD [Cur] BIGINT
END


IF EXISTS(SELECT * FROM SYSCOLUMNS WHERE id=object_id('Ca_Country') AND name='Capital')
BEGIN
 ALTER TABLE Ca_Country ALTER COLUMN [Capital] BIGINT
END
ELSE
BEGIN
 ALTER TABLE Ca_Country ADD [Capital] BIGINT
END


IF EXISTS(SELECT * FROM SYSCOLUMNS WHERE id=object_id('Ca_Country') AND name='Place')
BEGIN
 ALTER TABLE Ca_Country ALTER COLUMN [Place] BIGINT
END
ELSE
BEGIN
 ALTER TABLE Ca_Country ADD [Place] BIGINT
END


IF EXISTS(SELECT * FROM SYSCOLUMNS WHERE id=object_id('Ca_Country') AND name='Lang')
BEGIN
 ALTER TABLE Ca_Country ALTER COLUMN [Lang] BIGINT
END
ELSE
BEGIN
 ALTER TABLE Ca_Country ADD [Lang] BIGINT
END

-- [Ca_Cur] ----------------------
IF NOT EXISTS(SELECT * FROM sysobjects WHERE [name]='Ca_Cur' AND xtype='U')

BEGIN

    CREATE TABLE Ca_Cur ([ID] BIGINT NOT NULL
        ,[Createdat] BIGINT NOT NULL
        ,[Updatedat] BIGINT NOT NULL
        ,[Sort] BIGINT NOT NULL,
        [Code] NVARCHAR(16) COLLATE Chinese_PRC_CI_AS
        ,[Caption] NVARCHAR(64) COLLATE Chinese_PRC_CI_AS
        ,[Hidden] BIT
        ,[IsSac] BIT
        ,[IsTransfer] BIT
        ,[IsCash] BIT
        ,[EnableReward] BIT
        ,[EnableOTC] BIT
        ,[Icon] NVARCHAR(512) COLLATE Chinese_PRC_CI_AS
        ,[CurType] INT
        ,[Dec] BIGINT
        ,[AnchorRate] FLOAT
        ,[Freezable] BIT
        ,[Authorizable] BIT
        ,[ChaninID] NVARCHAR(256) COLLATE Chinese_PRC_CI_AS
        ,[ChaninName] NVARCHAR(256) COLLATE Chinese_PRC_CI_AS
        ,[ContractAddress] NVARCHAR(256) COLLATE Chinese_PRC_CI_AS
        ,[WalletAddress] NVARCHAR(256) COLLATE Chinese_PRC_CI_AS
        ,[BaseRate] FLOAT
, CONSTRAINT [PK_Ca_Cur] PRIMARY KEY CLUSTERED ([ID] ASC)) ON [PRIMARY]
END


IF EXISTS(SELECT * FROM SYSCOLUMNS WHERE id=object_id('Ca_Cur') AND name='Code')
BEGIN
 ALTER TABLE Ca_Cur ALTER COLUMN [Code] NVARCHAR(16) COLLATE Chinese_PRC_CI_AS
END
ELSE
BEGIN
 ALTER TABLE Ca_Cur ADD [Code] NVARCHAR(16) COLLATE Chinese_PRC_CI_AS
END


IF EXISTS(SELECT * FROM SYSCOLUMNS WHERE id=object_id('Ca_Cur') AND name='Caption')
BEGIN
 ALTER TABLE Ca_Cur ALTER COLUMN [Caption] NVARCHAR(64) COLLATE Chinese_PRC_CI_AS
END
ELSE
BEGIN
 ALTER TABLE Ca_Cur ADD [Caption] NVARCHAR(64) COLLATE Chinese_PRC_CI_AS
END


IF EXISTS(SELECT * FROM SYSCOLUMNS WHERE id=object_id('Ca_Cur') AND name='Hidden')
BEGIN
 ALTER TABLE Ca_Cur ALTER COLUMN [Hidden] BIT
END
ELSE
BEGIN
 ALTER TABLE Ca_Cur ADD [Hidden] BIT
END


IF EXISTS(SELECT * FROM SYSCOLUMNS WHERE id=object_id('Ca_Cur') AND name='IsSac')
BEGIN
 ALTER TABLE Ca_Cur ALTER COLUMN [IsSac] BIT
END
ELSE
BEGIN
 ALTER TABLE Ca_Cur ADD [IsSac] BIT
END


IF EXISTS(SELECT * FROM SYSCOLUMNS WHERE id=object_id('Ca_Cur') AND name='IsTransfer')
BEGIN
 ALTER TABLE Ca_Cur ALTER COLUMN [IsTransfer] BIT
END
ELSE
BEGIN
 ALTER TABLE Ca_Cur ADD [IsTransfer] BIT
END


IF EXISTS(SELECT * FROM SYSCOLUMNS WHERE id=object_id('Ca_Cur') AND name='IsCash')
BEGIN
 ALTER TABLE Ca_Cur ALTER COLUMN [IsCash] BIT
END
ELSE
BEGIN
 ALTER TABLE Ca_Cur ADD [IsCash] BIT
END


IF EXISTS(SELECT * FROM SYSCOLUMNS WHERE id=object_id('Ca_Cur') AND name='EnableReward')
BEGIN
 ALTER TABLE Ca_Cur ALTER COLUMN [EnableReward] BIT
END
ELSE
BEGIN
 ALTER TABLE Ca_Cur ADD [EnableReward] BIT
END


IF EXISTS(SELECT * FROM SYSCOLUMNS WHERE id=object_id('Ca_Cur') AND name='EnableOTC')
BEGIN
 ALTER TABLE Ca_Cur ALTER COLUMN [EnableOTC] BIT
END
ELSE
BEGIN
 ALTER TABLE Ca_Cur ADD [EnableOTC] BIT
END


IF EXISTS(SELECT * FROM SYSCOLUMNS WHERE id=object_id('Ca_Cur') AND name='Icon')
BEGIN
 ALTER TABLE Ca_Cur ALTER COLUMN [Icon] NVARCHAR(512) COLLATE Chinese_PRC_CI_AS
END
ELSE
BEGIN
 ALTER TABLE Ca_Cur ADD [Icon] NVARCHAR(512) COLLATE Chinese_PRC_CI_AS
END


IF EXISTS(SELECT * FROM SYSCOLUMNS WHERE id=object_id('Ca_Cur') AND name='CurType')
BEGIN
 ALTER TABLE Ca_Cur ALTER COLUMN [CurType] INT
END
ELSE
BEGIN
 ALTER TABLE Ca_Cur ADD [CurType] INT
END


IF EXISTS(SELECT * FROM SYSCOLUMNS WHERE id=object_id('Ca_Cur') AND name='Dec')
BEGIN
 ALTER TABLE Ca_Cur ALTER COLUMN [Dec] BIGINT
END
ELSE
BEGIN
 ALTER TABLE Ca_Cur ADD [Dec] BIGINT
END


IF EXISTS(SELECT * FROM SYSCOLUMNS WHERE id=object_id('Ca_Cur') AND name='AnchorRate')
BEGIN
 ALTER TABLE Ca_Cur ALTER COLUMN [AnchorRate] FLOAT
END
ELSE
BEGIN
 ALTER TABLE Ca_Cur ADD [AnchorRate] FLOAT
END


IF EXISTS(SELECT * FROM SYSCOLUMNS WHERE id=object_id('Ca_Cur') AND name='Freezable')
BEGIN
 ALTER TABLE Ca_Cur ALTER COLUMN [Freezable] BIT
END
ELSE
BEGIN
 ALTER TABLE Ca_Cur ADD [Freezable] BIT
END


IF EXISTS(SELECT * FROM SYSCOLUMNS WHERE id=object_id('Ca_Cur') AND name='Authorizable')
BEGIN
 ALTER TABLE Ca_Cur ALTER COLUMN [Authorizable] BIT
END
ELSE
BEGIN
 ALTER TABLE Ca_Cur ADD [Authorizable] BIT
END


IF EXISTS(SELECT * FROM SYSCOLUMNS WHERE id=object_id('Ca_Cur') AND name='ChaninID')
BEGIN
 ALTER TABLE Ca_Cur ALTER COLUMN [ChaninID] NVARCHAR(256) COLLATE Chinese_PRC_CI_AS
END
ELSE
BEGIN
 ALTER TABLE Ca_Cur ADD [ChaninID] NVARCHAR(256) COLLATE Chinese_PRC_CI_AS
END


IF EXISTS(SELECT * FROM SYSCOLUMNS WHERE id=object_id('Ca_Cur') AND name='ChaninName')
BEGIN
 ALTER TABLE Ca_Cur ALTER COLUMN [ChaninName] NVARCHAR(256) COLLATE Chinese_PRC_CI_AS
END
ELSE
BEGIN
 ALTER TABLE Ca_Cur ADD [ChaninName] NVARCHAR(256) COLLATE Chinese_PRC_CI_AS
END


IF EXISTS(SELECT * FROM SYSCOLUMNS WHERE id=object_id('Ca_Cur') AND name='ContractAddress')
BEGIN
 ALTER TABLE Ca_Cur ALTER COLUMN [ContractAddress] NVARCHAR(256) COLLATE Chinese_PRC_CI_AS
END
ELSE
BEGIN
 ALTER TABLE Ca_Cur ADD [ContractAddress] NVARCHAR(256) COLLATE Chinese_PRC_CI_AS
END


IF EXISTS(SELECT * FROM SYSCOLUMNS WHERE id=object_id('Ca_Cur') AND name='WalletAddress')
BEGIN
 ALTER TABLE Ca_Cur ALTER COLUMN [WalletAddress] NVARCHAR(256) COLLATE Chinese_PRC_CI_AS
END
ELSE
BEGIN
 ALTER TABLE Ca_Cur ADD [WalletAddress] NVARCHAR(256) COLLATE Chinese_PRC_CI_AS
END


IF EXISTS(SELECT * FROM SYSCOLUMNS WHERE id=object_id('Ca_Cur') AND name='BaseRate')
BEGIN
 ALTER TABLE Ca_Cur ALTER COLUMN [BaseRate] FLOAT
END
ELSE
BEGIN
 ALTER TABLE Ca_Cur ADD [BaseRate] FLOAT
END

-- [Ca_EndUser] ----------------------
IF NOT EXISTS(SELECT * FROM sysobjects WHERE [name]='Ca_EndUser' AND xtype='U')

BEGIN

    CREATE TABLE Ca_EndUser ([ID] BIGINT NOT NULL
        ,[Createdat] BIGINT NOT NULL
        ,[Updatedat] BIGINT NOT NULL
        ,[Sort] BIGINT NOT NULL,
        [Caption] NVARCHAR(64) COLLATE Chinese_PRC_CI_AS
        ,[Username] NVARCHAR(64) COLLATE Chinese_PRC_CI_AS
        ,[SocialAuthBiz] BIGINT
        ,[SocialAuthId] NVARCHAR(MAX)
        ,[Email] NVARCHAR(256) COLLATE Chinese_PRC_CI_AS
        ,[Tel] NVARCHAR(32) COLLATE Chinese_PRC_CI_AS
        ,[Gender] INT
        ,[Status] INT
        ,[Admin] INT
        ,[BizPartner] INT
        ,[Privilege] BIGINT
        ,[Verify] INT
        ,[Pwd] NVARCHAR(16) COLLATE Chinese_PRC_CI_AS
        ,[Online] BIT
        ,[Icon] NVARCHAR(256) COLLATE Chinese_PRC_CI_AS
        ,[Background] NVARCHAR(256) COLLATE Chinese_PRC_CI_AS
        ,[BasicAcct] BIGINT
        ,[Refer] NVARCHAR(7) COLLATE Chinese_PRC_CI_AS
        ,[Referer] BIGINT
        ,[Url] NVARCHAR(MAX)
        ,[About] NVARCHAR(MAX)
, CONSTRAINT [PK_Ca_EndUser] PRIMARY KEY CLUSTERED ([ID] ASC)) ON [PRIMARY]
END


IF EXISTS(SELECT * FROM SYSCOLUMNS WHERE id=object_id('Ca_EndUser') AND name='Caption')
BEGIN
 ALTER TABLE Ca_EndUser ALTER COLUMN [Caption] NVARCHAR(64) COLLATE Chinese_PRC_CI_AS
END
ELSE
BEGIN
 ALTER TABLE Ca_EndUser ADD [Caption] NVARCHAR(64) COLLATE Chinese_PRC_CI_AS
END


IF EXISTS(SELECT * FROM SYSCOLUMNS WHERE id=object_id('Ca_EndUser') AND name='Username')
BEGIN
 ALTER TABLE Ca_EndUser ALTER COLUMN [Username] NVARCHAR(64) COLLATE Chinese_PRC_CI_AS
END
ELSE
BEGIN
 ALTER TABLE Ca_EndUser ADD [Username] NVARCHAR(64) COLLATE Chinese_PRC_CI_AS
END


IF EXISTS(SELECT * FROM SYSCOLUMNS WHERE id=object_id('Ca_EndUser') AND name='SocialAuthBiz')
BEGIN
 ALTER TABLE Ca_EndUser ALTER COLUMN [SocialAuthBiz] BIGINT
END
ELSE
BEGIN
 ALTER TABLE Ca_EndUser ADD [SocialAuthBiz] BIGINT
END


IF EXISTS(SELECT * FROM SYSCOLUMNS WHERE id=object_id('Ca_EndUser') AND name='SocialAuthId')
BEGIN
 ALTER TABLE Ca_EndUser ALTER COLUMN [SocialAuthId] NVARCHAR(MAX)
END
ELSE
BEGIN
 ALTER TABLE Ca_EndUser ADD [SocialAuthId] NVARCHAR(MAX)
END


IF EXISTS(SELECT * FROM SYSCOLUMNS WHERE id=object_id('Ca_EndUser') AND name='Email')
BEGIN
 ALTER TABLE Ca_EndUser ALTER COLUMN [Email] NVARCHAR(256) COLLATE Chinese_PRC_CI_AS
END
ELSE
BEGIN
 ALTER TABLE Ca_EndUser ADD [Email] NVARCHAR(256) COLLATE Chinese_PRC_CI_AS
END


IF EXISTS(SELECT * FROM SYSCOLUMNS WHERE id=object_id('Ca_EndUser') AND name='Tel')
BEGIN
 ALTER TABLE Ca_EndUser ALTER COLUMN [Tel] NVARCHAR(32) COLLATE Chinese_PRC_CI_AS
END
ELSE
BEGIN
 ALTER TABLE Ca_EndUser ADD [Tel] NVARCHAR(32) COLLATE Chinese_PRC_CI_AS
END


IF EXISTS(SELECT * FROM SYSCOLUMNS WHERE id=object_id('Ca_EndUser') AND name='Gender')
BEGIN
 ALTER TABLE Ca_EndUser ALTER COLUMN [Gender] INT
END
ELSE
BEGIN
 ALTER TABLE Ca_EndUser ADD [Gender] INT
END


IF EXISTS(SELECT * FROM SYSCOLUMNS WHERE id=object_id('Ca_EndUser') AND name='Status')
BEGIN
 ALTER TABLE Ca_EndUser ALTER COLUMN [Status] INT
END
ELSE
BEGIN
 ALTER TABLE Ca_EndUser ADD [Status] INT
END


IF EXISTS(SELECT * FROM SYSCOLUMNS WHERE id=object_id('Ca_EndUser') AND name='Admin')
BEGIN
 ALTER TABLE Ca_EndUser ALTER COLUMN [Admin] INT
END
ELSE
BEGIN
 ALTER TABLE Ca_EndUser ADD [Admin] INT
END


IF EXISTS(SELECT * FROM SYSCOLUMNS WHERE id=object_id('Ca_EndUser') AND name='BizPartner')
BEGIN
 ALTER TABLE Ca_EndUser ALTER COLUMN [BizPartner] INT
END
ELSE
BEGIN
 ALTER TABLE Ca_EndUser ADD [BizPartner] INT
END


IF EXISTS(SELECT * FROM SYSCOLUMNS WHERE id=object_id('Ca_EndUser') AND name='Privilege')
BEGIN
 ALTER TABLE Ca_EndUser ALTER COLUMN [Privilege] BIGINT
END
ELSE
BEGIN
 ALTER TABLE Ca_EndUser ADD [Privilege] BIGINT
END


IF EXISTS(SELECT * FROM SYSCOLUMNS WHERE id=object_id('Ca_EndUser') AND name='Verify')
BEGIN
 ALTER TABLE Ca_EndUser ALTER COLUMN [Verify] INT
END
ELSE
BEGIN
 ALTER TABLE Ca_EndUser ADD [Verify] INT
END


IF EXISTS(SELECT * FROM SYSCOLUMNS WHERE id=object_id('Ca_EndUser') AND name='Pwd')
BEGIN
 ALTER TABLE Ca_EndUser ALTER COLUMN [Pwd] NVARCHAR(16) COLLATE Chinese_PRC_CI_AS
END
ELSE
BEGIN
 ALTER TABLE Ca_EndUser ADD [Pwd] NVARCHAR(16) COLLATE Chinese_PRC_CI_AS
END


IF EXISTS(SELECT * FROM SYSCOLUMNS WHERE id=object_id('Ca_EndUser') AND name='Online')
BEGIN
 ALTER TABLE Ca_EndUser ALTER COLUMN [Online] BIT
END
ELSE
BEGIN
 ALTER TABLE Ca_EndUser ADD [Online] BIT
END


IF EXISTS(SELECT * FROM SYSCOLUMNS WHERE id=object_id('Ca_EndUser') AND name='Icon')
BEGIN
 ALTER TABLE Ca_EndUser ALTER COLUMN [Icon] NVARCHAR(256) COLLATE Chinese_PRC_CI_AS
END
ELSE
BEGIN
 ALTER TABLE Ca_EndUser ADD [Icon] NVARCHAR(256) COLLATE Chinese_PRC_CI_AS
END


IF EXISTS(SELECT * FROM SYSCOLUMNS WHERE id=object_id('Ca_EndUser') AND name='Background')
BEGIN
 ALTER TABLE Ca_EndUser ALTER COLUMN [Background] NVARCHAR(256) COLLATE Chinese_PRC_CI_AS
END
ELSE
BEGIN
 ALTER TABLE Ca_EndUser ADD [Background] NVARCHAR(256) COLLATE Chinese_PRC_CI_AS
END


IF EXISTS(SELECT * FROM SYSCOLUMNS WHERE id=object_id('Ca_EndUser') AND name='BasicAcct')
BEGIN
 ALTER TABLE Ca_EndUser ALTER COLUMN [BasicAcct] BIGINT
END
ELSE
BEGIN
 ALTER TABLE Ca_EndUser ADD [BasicAcct] BIGINT
END


IF EXISTS(SELECT * FROM SYSCOLUMNS WHERE id=object_id('Ca_EndUser') AND name='Refer')
BEGIN
 ALTER TABLE Ca_EndUser ALTER COLUMN [Refer] NVARCHAR(7) COLLATE Chinese_PRC_CI_AS
END
ELSE
BEGIN
 ALTER TABLE Ca_EndUser ADD [Refer] NVARCHAR(7) COLLATE Chinese_PRC_CI_AS
END


IF EXISTS(SELECT * FROM SYSCOLUMNS WHERE id=object_id('Ca_EndUser') AND name='Referer')
BEGIN
 ALTER TABLE Ca_EndUser ALTER COLUMN [Referer] BIGINT
END
ELSE
BEGIN
 ALTER TABLE Ca_EndUser ADD [Referer] BIGINT
END


IF EXISTS(SELECT * FROM SYSCOLUMNS WHERE id=object_id('Ca_EndUser') AND name='Url')
BEGIN
 ALTER TABLE Ca_EndUser ALTER COLUMN [Url] NVARCHAR(MAX)
END
ELSE
BEGIN
 ALTER TABLE Ca_EndUser ADD [Url] NVARCHAR(MAX)
END


IF EXISTS(SELECT * FROM SYSCOLUMNS WHERE id=object_id('Ca_EndUser') AND name='About')
BEGIN
 ALTER TABLE Ca_EndUser ALTER COLUMN [About] NVARCHAR(MAX)
END
ELSE
BEGIN
 ALTER TABLE Ca_EndUser ADD [About] NVARCHAR(MAX)
END

-- [Ca_File] ----------------------
IF NOT EXISTS(SELECT * FROM sysobjects WHERE [name]='Ca_File' AND xtype='U')

BEGIN

    CREATE TABLE Ca_File ([ID] BIGINT NOT NULL
        ,[Createdat] BIGINT NOT NULL
        ,[Updatedat] BIGINT NOT NULL
        ,[Sort] BIGINT NOT NULL,
        [Caption] NVARCHAR(256) COLLATE Chinese_PRC_CI_AS
        ,[Encrypt] INT
        ,[SHA256] NVARCHAR(MAX)
        ,[Size] BIGINT
        ,[Bind] BIGINT
        ,[BindType] INT
        ,[State] INT
        ,[Folder] BIGINT
        ,[FileType] INT
        ,[JSON] NVARCHAR(MAX)
, CONSTRAINT [PK_Ca_File] PRIMARY KEY CLUSTERED ([ID] ASC)) ON [PRIMARY]
END


IF EXISTS(SELECT * FROM SYSCOLUMNS WHERE id=object_id('Ca_File') AND name='Caption')
BEGIN
 ALTER TABLE Ca_File ALTER COLUMN [Caption] NVARCHAR(256) COLLATE Chinese_PRC_CI_AS
END
ELSE
BEGIN
 ALTER TABLE Ca_File ADD [Caption] NVARCHAR(256) COLLATE Chinese_PRC_CI_AS
END


IF EXISTS(SELECT * FROM SYSCOLUMNS WHERE id=object_id('Ca_File') AND name='Encrypt')
BEGIN
 ALTER TABLE Ca_File ALTER COLUMN [Encrypt] INT
END
ELSE
BEGIN
 ALTER TABLE Ca_File ADD [Encrypt] INT
END


IF EXISTS(SELECT * FROM SYSCOLUMNS WHERE id=object_id('Ca_File') AND name='SHA256')
BEGIN
 ALTER TABLE Ca_File ALTER COLUMN [SHA256] NVARCHAR(MAX)
END
ELSE
BEGIN
 ALTER TABLE Ca_File ADD [SHA256] NVARCHAR(MAX)
END


IF EXISTS(SELECT * FROM SYSCOLUMNS WHERE id=object_id('Ca_File') AND name='Size')
BEGIN
 ALTER TABLE Ca_File ALTER COLUMN [Size] BIGINT
END
ELSE
BEGIN
 ALTER TABLE Ca_File ADD [Size] BIGINT
END


IF EXISTS(SELECT * FROM SYSCOLUMNS WHERE id=object_id('Ca_File') AND name='Bind')
BEGIN
 ALTER TABLE Ca_File ALTER COLUMN [Bind] BIGINT
END
ELSE
BEGIN
 ALTER TABLE Ca_File ADD [Bind] BIGINT
END


IF EXISTS(SELECT * FROM SYSCOLUMNS WHERE id=object_id('Ca_File') AND name='BindType')
BEGIN
 ALTER TABLE Ca_File ALTER COLUMN [BindType] INT
END
ELSE
BEGIN
 ALTER TABLE Ca_File ADD [BindType] INT
END


IF EXISTS(SELECT * FROM SYSCOLUMNS WHERE id=object_id('Ca_File') AND name='State')
BEGIN
 ALTER TABLE Ca_File ALTER COLUMN [State] INT
END
ELSE
BEGIN
 ALTER TABLE Ca_File ADD [State] INT
END


IF EXISTS(SELECT * FROM SYSCOLUMNS WHERE id=object_id('Ca_File') AND name='Folder')
BEGIN
 ALTER TABLE Ca_File ALTER COLUMN [Folder] BIGINT
END
ELSE
BEGIN
 ALTER TABLE Ca_File ADD [Folder] BIGINT
END


IF EXISTS(SELECT * FROM SYSCOLUMNS WHERE id=object_id('Ca_File') AND name='FileType')
BEGIN
 ALTER TABLE Ca_File ALTER COLUMN [FileType] INT
END
ELSE
BEGIN
 ALTER TABLE Ca_File ADD [FileType] INT
END


IF EXISTS(SELECT * FROM SYSCOLUMNS WHERE id=object_id('Ca_File') AND name='JSON')
BEGIN
 ALTER TABLE Ca_File ALTER COLUMN [JSON] NVARCHAR(MAX)
END
ELSE
BEGIN
 ALTER TABLE Ca_File ADD [JSON] NVARCHAR(MAX)
END

-- [Ca_Folder] ----------------------
IF NOT EXISTS(SELECT * FROM sysobjects WHERE [name]='Ca_Folder' AND xtype='U')

BEGIN

    CREATE TABLE Ca_Folder ([ID] BIGINT NOT NULL
        ,[Createdat] BIGINT NOT NULL
        ,[Updatedat] BIGINT NOT NULL
        ,[Sort] BIGINT NOT NULL,
        [Caption] NVARCHAR(256) COLLATE Chinese_PRC_CI_AS
        ,[Encrypt] INT
        ,[Bind] BIGINT
        ,[BindType] INT
        ,[Parent] BIGINT
, CONSTRAINT [PK_Ca_Folder] PRIMARY KEY CLUSTERED ([ID] ASC)) ON [PRIMARY]
END


IF EXISTS(SELECT * FROM SYSCOLUMNS WHERE id=object_id('Ca_Folder') AND name='Caption')
BEGIN
 ALTER TABLE Ca_Folder ALTER COLUMN [Caption] NVARCHAR(256) COLLATE Chinese_PRC_CI_AS
END
ELSE
BEGIN
 ALTER TABLE Ca_Folder ADD [Caption] NVARCHAR(256) COLLATE Chinese_PRC_CI_AS
END


IF EXISTS(SELECT * FROM SYSCOLUMNS WHERE id=object_id('Ca_Folder') AND name='Encrypt')
BEGIN
 ALTER TABLE Ca_Folder ALTER COLUMN [Encrypt] INT
END
ELSE
BEGIN
 ALTER TABLE Ca_Folder ADD [Encrypt] INT
END


IF EXISTS(SELECT * FROM SYSCOLUMNS WHERE id=object_id('Ca_Folder') AND name='Bind')
BEGIN
 ALTER TABLE Ca_Folder ALTER COLUMN [Bind] BIGINT
END
ELSE
BEGIN
 ALTER TABLE Ca_Folder ADD [Bind] BIGINT
END


IF EXISTS(SELECT * FROM SYSCOLUMNS WHERE id=object_id('Ca_Folder') AND name='BindType')
BEGIN
 ALTER TABLE Ca_Folder ALTER COLUMN [BindType] INT
END
ELSE
BEGIN
 ALTER TABLE Ca_Folder ADD [BindType] INT
END


IF EXISTS(SELECT * FROM SYSCOLUMNS WHERE id=object_id('Ca_Folder') AND name='Parent')
BEGIN
 ALTER TABLE Ca_Folder ALTER COLUMN [Parent] BIGINT
END
ELSE
BEGIN
 ALTER TABLE Ca_Folder ADD [Parent] BIGINT
END

-- [Ca_Lang] ----------------------
IF NOT EXISTS(SELECT * FROM sysobjects WHERE [name]='Ca_Lang' AND xtype='U')

BEGIN

    CREATE TABLE Ca_Lang ([ID] BIGINT NOT NULL
        ,[Createdat] BIGINT NOT NULL
        ,[Updatedat] BIGINT NOT NULL
        ,[Sort] BIGINT NOT NULL,
        [Code2] NVARCHAR(2) COLLATE Chinese_PRC_CI_AS
        ,[Caption] NVARCHAR(64) COLLATE Chinese_PRC_CI_AS
        ,[Native] NVARCHAR(64) COLLATE Chinese_PRC_CI_AS
        ,[Icon] NVARCHAR(256) COLLATE Chinese_PRC_CI_AS
        ,[IsBlank] BIT
        ,[IsLocale] BIT
        ,[IsContent] BIT
        ,[IsAutoTranslate] BIT
        ,[TextDirection] INT
, CONSTRAINT [PK_Ca_Lang] PRIMARY KEY CLUSTERED ([ID] ASC)) ON [PRIMARY]
END


IF EXISTS(SELECT * FROM SYSCOLUMNS WHERE id=object_id('Ca_Lang') AND name='Code2')
BEGIN
 ALTER TABLE Ca_Lang ALTER COLUMN [Code2] NVARCHAR(2) COLLATE Chinese_PRC_CI_AS
END
ELSE
BEGIN
 ALTER TABLE Ca_Lang ADD [Code2] NVARCHAR(2) COLLATE Chinese_PRC_CI_AS
END


IF EXISTS(SELECT * FROM SYSCOLUMNS WHERE id=object_id('Ca_Lang') AND name='Caption')
BEGIN
 ALTER TABLE Ca_Lang ALTER COLUMN [Caption] NVARCHAR(64) COLLATE Chinese_PRC_CI_AS
END
ELSE
BEGIN
 ALTER TABLE Ca_Lang ADD [Caption] NVARCHAR(64) COLLATE Chinese_PRC_CI_AS
END


IF EXISTS(SELECT * FROM SYSCOLUMNS WHERE id=object_id('Ca_Lang') AND name='Native')
BEGIN
 ALTER TABLE Ca_Lang ALTER COLUMN [Native] NVARCHAR(64) COLLATE Chinese_PRC_CI_AS
END
ELSE
BEGIN
 ALTER TABLE Ca_Lang ADD [Native] NVARCHAR(64) COLLATE Chinese_PRC_CI_AS
END


IF EXISTS(SELECT * FROM SYSCOLUMNS WHERE id=object_id('Ca_Lang') AND name='Icon')
BEGIN
 ALTER TABLE Ca_Lang ALTER COLUMN [Icon] NVARCHAR(256) COLLATE Chinese_PRC_CI_AS
END
ELSE
BEGIN
 ALTER TABLE Ca_Lang ADD [Icon] NVARCHAR(256) COLLATE Chinese_PRC_CI_AS
END


IF EXISTS(SELECT * FROM SYSCOLUMNS WHERE id=object_id('Ca_Lang') AND name='IsBlank')
BEGIN
 ALTER TABLE Ca_Lang ALTER COLUMN [IsBlank] BIT
END
ELSE
BEGIN
 ALTER TABLE Ca_Lang ADD [IsBlank] BIT
END


IF EXISTS(SELECT * FROM SYSCOLUMNS WHERE id=object_id('Ca_Lang') AND name='IsLocale')
BEGIN
 ALTER TABLE Ca_Lang ALTER COLUMN [IsLocale] BIT
END
ELSE
BEGIN
 ALTER TABLE Ca_Lang ADD [IsLocale] BIT
END


IF EXISTS(SELECT * FROM SYSCOLUMNS WHERE id=object_id('Ca_Lang') AND name='IsContent')
BEGIN
 ALTER TABLE Ca_Lang ALTER COLUMN [IsContent] BIT
END
ELSE
BEGIN
 ALTER TABLE Ca_Lang ADD [IsContent] BIT
END


IF EXISTS(SELECT * FROM SYSCOLUMNS WHERE id=object_id('Ca_Lang') AND name='IsAutoTranslate')
BEGIN
 ALTER TABLE Ca_Lang ALTER COLUMN [IsAutoTranslate] BIT
END
ELSE
BEGIN
 ALTER TABLE Ca_Lang ADD [IsAutoTranslate] BIT
END


IF EXISTS(SELECT * FROM SYSCOLUMNS WHERE id=object_id('Ca_Lang') AND name='TextDirection')
BEGIN
 ALTER TABLE Ca_Lang ALTER COLUMN [TextDirection] INT
END
ELSE
BEGIN
 ALTER TABLE Ca_Lang ADD [TextDirection] INT
END

-- [Ca_WebCredential] ----------------------
IF NOT EXISTS(SELECT * FROM sysobjects WHERE [name]='Ca_WebCredential' AND xtype='U')

BEGIN

    CREATE TABLE Ca_WebCredential ([ID] BIGINT NOT NULL
        ,[Createdat] BIGINT NOT NULL
        ,[Updatedat] BIGINT NOT NULL
        ,[Sort] BIGINT NOT NULL,
        [Caption] NVARCHAR(64) COLLATE Chinese_PRC_CI_AS
        ,[ExternalId] BIGINT
        ,[Icon] NVARCHAR(256) COLLATE Chinese_PRC_CI_AS
        ,[EU] BIGINT
        ,[Biz] BIGINT
        ,[Json] NVARCHAR(MAX)
, CONSTRAINT [PK_Ca_WebCredential] PRIMARY KEY CLUSTERED ([ID] ASC)) ON [PRIMARY]
END


IF EXISTS(SELECT * FROM SYSCOLUMNS WHERE id=object_id('Ca_WebCredential') AND name='Caption')
BEGIN
 ALTER TABLE Ca_WebCredential ALTER COLUMN [Caption] NVARCHAR(64) COLLATE Chinese_PRC_CI_AS
END
ELSE
BEGIN
 ALTER TABLE Ca_WebCredential ADD [Caption] NVARCHAR(64) COLLATE Chinese_PRC_CI_AS
END


IF EXISTS(SELECT * FROM SYSCOLUMNS WHERE id=object_id('Ca_WebCredential') AND name='ExternalId')
BEGIN
 ALTER TABLE Ca_WebCredential ALTER COLUMN [ExternalId] BIGINT
END
ELSE
BEGIN
 ALTER TABLE Ca_WebCredential ADD [ExternalId] BIGINT
END


IF EXISTS(SELECT * FROM SYSCOLUMNS WHERE id=object_id('Ca_WebCredential') AND name='Icon')
BEGIN
 ALTER TABLE Ca_WebCredential ALTER COLUMN [Icon] NVARCHAR(256) COLLATE Chinese_PRC_CI_AS
END
ELSE
BEGIN
 ALTER TABLE Ca_WebCredential ADD [Icon] NVARCHAR(256) COLLATE Chinese_PRC_CI_AS
END


IF EXISTS(SELECT * FROM SYSCOLUMNS WHERE id=object_id('Ca_WebCredential') AND name='EU')
BEGIN
 ALTER TABLE Ca_WebCredential ALTER COLUMN [EU] BIGINT
END
ELSE
BEGIN
 ALTER TABLE Ca_WebCredential ADD [EU] BIGINT
END


IF EXISTS(SELECT * FROM SYSCOLUMNS WHERE id=object_id('Ca_WebCredential') AND name='Biz')
BEGIN
 ALTER TABLE Ca_WebCredential ALTER COLUMN [Biz] BIGINT
END
ELSE
BEGIN
 ALTER TABLE Ca_WebCredential ADD [Biz] BIGINT
END


IF EXISTS(SELECT * FROM SYSCOLUMNS WHERE id=object_id('Ca_WebCredential') AND name='Json')
BEGIN
 ALTER TABLE Ca_WebCredential ALTER COLUMN [Json] NVARCHAR(MAX)
END
ELSE
BEGIN
 ALTER TABLE Ca_WebCredential ADD [Json] NVARCHAR(MAX)
END

-- [Core_BizOwner] ----------------------
IF NOT EXISTS(SELECT * FROM sysobjects WHERE [name]='Core_BizOwner' AND xtype='U')

BEGIN

    CREATE TABLE Core_BizOwner ([ID] BIGINT NOT NULL
        ,[Createdat] BIGINT NOT NULL
        ,[Updatedat] BIGINT NOT NULL
        ,[Sort] BIGINT NOT NULL,
        [Caption] NVARCHAR(64) COLLATE Chinese_PRC_CI_AS
        ,[Bind] BIGINT
        ,[BindType] INT
        ,[State] INT
, CONSTRAINT [PK_Core_BizOwner] PRIMARY KEY CLUSTERED ([ID] ASC)) ON [PRIMARY]
END


IF EXISTS(SELECT * FROM SYSCOLUMNS WHERE id=object_id('Core_BizOwner') AND name='Caption')
BEGIN
 ALTER TABLE Core_BizOwner ALTER COLUMN [Caption] NVARCHAR(64) COLLATE Chinese_PRC_CI_AS
END
ELSE
BEGIN
 ALTER TABLE Core_BizOwner ADD [Caption] NVARCHAR(64) COLLATE Chinese_PRC_CI_AS
END


IF EXISTS(SELECT * FROM SYSCOLUMNS WHERE id=object_id('Core_BizOwner') AND name='Bind')
BEGIN
 ALTER TABLE Core_BizOwner ALTER COLUMN [Bind] BIGINT
END
ELSE
BEGIN
 ALTER TABLE Core_BizOwner ADD [Bind] BIGINT
END


IF EXISTS(SELECT * FROM SYSCOLUMNS WHERE id=object_id('Core_BizOwner') AND name='BindType')
BEGIN
 ALTER TABLE Core_BizOwner ALTER COLUMN [BindType] INT
END
ELSE
BEGIN
 ALTER TABLE Core_BizOwner ADD [BindType] INT
END


IF EXISTS(SELECT * FROM SYSCOLUMNS WHERE id=object_id('Core_BizOwner') AND name='State')
BEGIN
 ALTER TABLE Core_BizOwner ALTER COLUMN [State] INT
END
ELSE
BEGIN
 ALTER TABLE Core_BizOwner ADD [State] INT
END

-- [Core_CryptoLink] ----------------------
IF NOT EXISTS(SELECT * FROM sysobjects WHERE [name]='Core_CryptoLink' AND xtype='U')

BEGIN

    CREATE TABLE Core_CryptoLink ([ID] BIGINT NOT NULL
        ,[Createdat] BIGINT NOT NULL
        ,[Updatedat] BIGINT NOT NULL
        ,[Sort] BIGINT NOT NULL,
        [Expiry] BIGINT
        ,[HashFull] NVARCHAR(64) COLLATE Chinese_PRC_CI_AS
        ,[HashTiny] NVARCHAR(9) COLLATE Chinese_PRC_CI_AS
        ,[Src] NVARCHAR(MAX)
        ,[DomainName] BIGINT
        ,[Owner] BIGINT
        ,[Dst] BIGINT
        ,[BizOwner] BIGINT
        ,[Data] NVARCHAR(MAX)
        ,[OgTitle] NVARCHAR(MAX)
        ,[OgDesc] NVARCHAR(MAX)
        ,[OgImg] NVARCHAR(MAX)
, CONSTRAINT [PK_Core_CryptoLink] PRIMARY KEY CLUSTERED ([ID] ASC)) ON [PRIMARY]
END


IF EXISTS(SELECT * FROM SYSCOLUMNS WHERE id=object_id('Core_CryptoLink') AND name='Expiry')
BEGIN
 ALTER TABLE Core_CryptoLink ALTER COLUMN [Expiry] BIGINT
END
ELSE
BEGIN
 ALTER TABLE Core_CryptoLink ADD [Expiry] BIGINT
END


IF EXISTS(SELECT * FROM SYSCOLUMNS WHERE id=object_id('Core_CryptoLink') AND name='HashFull')
BEGIN
 ALTER TABLE Core_CryptoLink ALTER COLUMN [HashFull] NVARCHAR(64) COLLATE Chinese_PRC_CI_AS
END
ELSE
BEGIN
 ALTER TABLE Core_CryptoLink ADD [HashFull] NVARCHAR(64) COLLATE Chinese_PRC_CI_AS
END


IF EXISTS(SELECT * FROM SYSCOLUMNS WHERE id=object_id('Core_CryptoLink') AND name='HashTiny')
BEGIN
 ALTER TABLE Core_CryptoLink ALTER COLUMN [HashTiny] NVARCHAR(9) COLLATE Chinese_PRC_CI_AS
END
ELSE
BEGIN
 ALTER TABLE Core_CryptoLink ADD [HashTiny] NVARCHAR(9) COLLATE Chinese_PRC_CI_AS
END


IF EXISTS(SELECT * FROM SYSCOLUMNS WHERE id=object_id('Core_CryptoLink') AND name='Src')
BEGIN
 ALTER TABLE Core_CryptoLink ALTER COLUMN [Src] NVARCHAR(MAX)
END
ELSE
BEGIN
 ALTER TABLE Core_CryptoLink ADD [Src] NVARCHAR(MAX)
END


IF EXISTS(SELECT * FROM SYSCOLUMNS WHERE id=object_id('Core_CryptoLink') AND name='DomainName')
BEGIN
 ALTER TABLE Core_CryptoLink ALTER COLUMN [DomainName] BIGINT
END
ELSE
BEGIN
 ALTER TABLE Core_CryptoLink ADD [DomainName] BIGINT
END


IF EXISTS(SELECT * FROM SYSCOLUMNS WHERE id=object_id('Core_CryptoLink') AND name='Owner')
BEGIN
 ALTER TABLE Core_CryptoLink ALTER COLUMN [Owner] BIGINT
END
ELSE
BEGIN
 ALTER TABLE Core_CryptoLink ADD [Owner] BIGINT
END


IF EXISTS(SELECT * FROM SYSCOLUMNS WHERE id=object_id('Core_CryptoLink') AND name='Dst')
BEGIN
 ALTER TABLE Core_CryptoLink ALTER COLUMN [Dst] BIGINT
END
ELSE
BEGIN
 ALTER TABLE Core_CryptoLink ADD [Dst] BIGINT
END


IF EXISTS(SELECT * FROM SYSCOLUMNS WHERE id=object_id('Core_CryptoLink') AND name='BizOwner')
BEGIN
 ALTER TABLE Core_CryptoLink ALTER COLUMN [BizOwner] BIGINT
END
ELSE
BEGIN
 ALTER TABLE Core_CryptoLink ADD [BizOwner] BIGINT
END


IF EXISTS(SELECT * FROM SYSCOLUMNS WHERE id=object_id('Core_CryptoLink') AND name='Data')
BEGIN
 ALTER TABLE Core_CryptoLink ALTER COLUMN [Data] NVARCHAR(MAX)
END
ELSE
BEGIN
 ALTER TABLE Core_CryptoLink ADD [Data] NVARCHAR(MAX)
END


IF EXISTS(SELECT * FROM SYSCOLUMNS WHERE id=object_id('Core_CryptoLink') AND name='OgTitle')
BEGIN
 ALTER TABLE Core_CryptoLink ALTER COLUMN [OgTitle] NVARCHAR(MAX)
END
ELSE
BEGIN
 ALTER TABLE Core_CryptoLink ADD [OgTitle] NVARCHAR(MAX)
END


IF EXISTS(SELECT * FROM SYSCOLUMNS WHERE id=object_id('Core_CryptoLink') AND name='OgDesc')
BEGIN
 ALTER TABLE Core_CryptoLink ALTER COLUMN [OgDesc] NVARCHAR(MAX)
END
ELSE
BEGIN
 ALTER TABLE Core_CryptoLink ADD [OgDesc] NVARCHAR(MAX)
END


IF EXISTS(SELECT * FROM SYSCOLUMNS WHERE id=object_id('Core_CryptoLink') AND name='OgImg')
BEGIN
 ALTER TABLE Core_CryptoLink ALTER COLUMN [OgImg] NVARCHAR(MAX)
END
ELSE
BEGIN
 ALTER TABLE Core_CryptoLink ADD [OgImg] NVARCHAR(MAX)
END

-- [Core_DomainName] ----------------------
IF NOT EXISTS(SELECT * FROM sysobjects WHERE [name]='Core_DomainName' AND xtype='U')

BEGIN

    CREATE TABLE Core_DomainName ([ID] BIGINT NOT NULL
        ,[Createdat] BIGINT NOT NULL
        ,[Updatedat] BIGINT NOT NULL
        ,[Sort] BIGINT NOT NULL,
        [Caption] NVARCHAR(64) COLLATE Chinese_PRC_CI_AS
        ,[Biz] BIGINT
        ,[EndUser] BIGINT
        ,[BizOwner] BIGINT
, CONSTRAINT [PK_Core_DomainName] PRIMARY KEY CLUSTERED ([ID] ASC)) ON [PRIMARY]
END


IF EXISTS(SELECT * FROM SYSCOLUMNS WHERE id=object_id('Core_DomainName') AND name='Caption')
BEGIN
 ALTER TABLE Core_DomainName ALTER COLUMN [Caption] NVARCHAR(64) COLLATE Chinese_PRC_CI_AS
END
ELSE
BEGIN
 ALTER TABLE Core_DomainName ADD [Caption] NVARCHAR(64) COLLATE Chinese_PRC_CI_AS
END


IF EXISTS(SELECT * FROM SYSCOLUMNS WHERE id=object_id('Core_DomainName') AND name='Biz')
BEGIN
 ALTER TABLE Core_DomainName ALTER COLUMN [Biz] BIGINT
END
ELSE
BEGIN
 ALTER TABLE Core_DomainName ADD [Biz] BIGINT
END


IF EXISTS(SELECT * FROM SYSCOLUMNS WHERE id=object_id('Core_DomainName') AND name='EndUser')
BEGIN
 ALTER TABLE Core_DomainName ALTER COLUMN [EndUser] BIGINT
END
ELSE
BEGIN
 ALTER TABLE Core_DomainName ADD [EndUser] BIGINT
END


IF EXISTS(SELECT * FROM SYSCOLUMNS WHERE id=object_id('Core_DomainName') AND name='BizOwner')
BEGIN
 ALTER TABLE Core_DomainName ALTER COLUMN [BizOwner] BIGINT
END
ELSE
BEGIN
 ALTER TABLE Core_DomainName ADD [BizOwner] BIGINT
END

-- [Sys_Log] ----------------------
IF NOT EXISTS(SELECT * FROM sysobjects WHERE [name]='Sys_Log' AND xtype='U')

BEGIN

    CREATE TABLE Sys_Log ([ID] BIGINT NOT NULL
        ,[Createdat] BIGINT NOT NULL
        ,[Updatedat] BIGINT NOT NULL
        ,[Sort] BIGINT NOT NULL,
        [Location] NVARCHAR(MAX)
        ,[Content] NVARCHAR(MAX)
        ,[Sql] NVARCHAR(MAX)
, CONSTRAINT [PK_Sys_Log] PRIMARY KEY CLUSTERED ([ID] ASC)) ON [PRIMARY]
END


IF EXISTS(SELECT * FROM SYSCOLUMNS WHERE id=object_id('Sys_Log') AND name='Location')
BEGIN
 ALTER TABLE Sys_Log ALTER COLUMN [Location] NVARCHAR(MAX)
END
ELSE
BEGIN
 ALTER TABLE Sys_Log ADD [Location] NVARCHAR(MAX)
END


IF EXISTS(SELECT * FROM SYSCOLUMNS WHERE id=object_id('Sys_Log') AND name='Content')
BEGIN
 ALTER TABLE Sys_Log ALTER COLUMN [Content] NVARCHAR(MAX)
END
ELSE
BEGIN
 ALTER TABLE Sys_Log ADD [Content] NVARCHAR(MAX)
END


IF EXISTS(SELECT * FROM SYSCOLUMNS WHERE id=object_id('Sys_Log') AND name='Sql')
BEGIN
 ALTER TABLE Sys_Log ALTER COLUMN [Sql] NVARCHAR(MAX)
END
ELSE
BEGIN
 ALTER TABLE Sys_Log ADD [Sql] NVARCHAR(MAX)
END
